import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";

const DAY_OFFSET: Record<string, number> = {
  Monday: 0,
  Tuesday: 1,
  Wednesday: 2,
  Thursday: 3,
  Friday: 4,
  Saturday: 5,
  Sunday: 6,
};
const DAY_MAP: Record<string, string> = {
  Monday: "MO",
  Tuesday: "TU",
  Wednesday: "WE",
  Thursday: "TH",
  Friday: "FR",
  Saturday: "SA",
  Sunday: "SU",
};

function getNextDayOfWeek(startDate: Date, dayName: string): Date {
  const date = new Date(startDate);
  const startDow = date.getDay(); // 0=Sun
  const targetDow = (DAY_OFFSET[dayName] ?? 0) + 1; // Mon=1
  let diff = targetDow - startDow;
  if (diff < 0) diff += 7;
  date.setDate(date.getDate() + diff);
  return date;
}

export async function POST(req: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session || !session.user) {
      return NextResponse.json(
        { message: "Please log in to sync your schedule." },
        { status: 401 }
      );
    }

    // @ts-ignore
    const accessToken = session.accessToken;
    if (!accessToken) {
      return NextResponse.json(
        { message: "Please log in with Google to enable calendar sync." },
        { status: 401 }
      );
    }

    const body = await req.json();
    const { variant, constraints, semesterStart, semesterEnd } = body;

    if (!variant || !constraints || !semesterStart || !semesterEnd) {
      return NextResponse.json({ message: "Missing required fields." }, { status: 400 });
    }

    const startDate = new Date(semesterStart);
    const endDate = new Date(semesterEnd);
    const endDateStr = `${endDate.getFullYear()}${String(endDate.getMonth() + 1).padStart(2, '0')}${String(endDate.getDate()).padStart(2, '0')}T235959Z`;

    // 1. Create a new Google Calendar
    const calendarRes = await fetch("https://www.googleapis.com/calendar/v3/calendars", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        summary: `${variant.name} — Schedulr AI`,
        description: `Exported from Schedulr AI on ${new Date().toLocaleDateString()}`,
        timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone,
      }),
    });

    if (!calendarRes.ok) {
      const errText = await calendarRes.text();
      console.error("GCal Create Calendar Error:", errText);
      return NextResponse.json({ message: "Failed to create Google Calendar. Did you grant permissions?" }, { status: 500 });
    }

    const calendarData = await calendarRes.json();
    const calendarId = calendarData.id;

    // 2. Prepare events
    const eventsToCreate = [];
    const timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;

    for (const slot of variant.slots) {
      const match = slot.slotLabel.match(/(\d{2}:\d{2})\s*[–-]\s*(\d{2}:\d{2})/);
      const startTime = match?.[1] ?? "09:00";
      const endTime = match?.[2] ?? "09:50";

      const dayCode = DAY_MAP[slot.day];
      if (!dayCode) continue;

      const firstOccurrence = getNextDayOfWeek(startDate, slot.day);
      const [startH, startM] = startTime.split(":").map(Number);
      const [endH, endM] = endTime.split(":").map(Number);

      firstOccurrence.setHours(startH, startM, 0, 0);
      const eventEnd = new Date(firstOccurrence);
      eventEnd.setHours(endH, endM, 0, 0);

      eventsToCreate.push({
        summary: slot.subject,
        location: slot.room,
        description: `Faculty: ${slot.faculty}\nRoom: ${slot.room}\nGenerated by Schedulr AI`,
        start: {
          dateTime: firstOccurrence.toISOString(),
          timeZone,
        },
        end: {
          dateTime: eventEnd.toISOString(),
          timeZone,
        },
        recurrence: [
          `RRULE:FREQ=WEEKLY;BYDAY=${dayCode};UNTIL=${endDateStr}`
        ],
      });
    }

    // 3. Insert events directly (concurrency limited to avoid rate limits)
    let successCount = 0;
    const CHUNK_SIZE = 5;
    for (let i = 0; i < eventsToCreate.length; i += CHUNK_SIZE) {
      const chunk = eventsToCreate.slice(i, i + CHUNK_SIZE);
      await Promise.all(
        chunk.map(async (event) => {
          try {
            const res = await fetch(`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(calendarId)}/events`, {
              method: "POST",
              headers: {
                Authorization: `Bearer ${accessToken}`,
                "Content-Type": "application/json",
              },
              body: JSON.stringify(event),
            });
            if (res.ok) successCount++;
          } catch (e) {
             console.error("Failed to insert event", e);
          }
        })
      );
    }

    return NextResponse.json({
      message: "Successfully exported to Google Calendar.",
      calendarId,
      eventsCreated: successCount,
      calendarLink: `https://calendar.google.com/calendar/u/0/r?cid=${encodeURIComponent(calendarId)}`
    });
  } catch (error) {
    console.error("Google Calendar export error:", error);
    return NextResponse.json(
      { message: "An unexpected error occurred during export." },
      { status: 500 }
    );
  }
}


