"use client";

import { useState } from "react";
import { CalendarPlus, Download, Loader2 } from "lucide-react";
import { toast } from "sonner";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import type { TimetableVariant, SchedulerConstraints } from "@/lib/types";

interface CalendarExportDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  variant: TimetableVariant | null;
  constraints: SchedulerConstraints;
  slotLabels: string[];
}

const DAY_MAP: Record<string, string> = {
  Monday: "MO",
  Tuesday: "TU",
  Wednesday: "WE",
  Thursday: "TH",
  Friday: "FR",
  Saturday: "SA",
  Sunday: "SU",
};

const DAY_OFFSET: Record<string, number> = {
  Monday: 0,
  Tuesday: 1,
  Wednesday: 2,
  Thursday: 3,
  Friday: 4,
  Saturday: 5,
  Sunday: 6,
};

function formatICSDate(date: Date): string {
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${date.getFullYear()}${pad(date.getMonth() + 1)}${pad(date.getDate())}T${pad(date.getHours())}${pad(date.getMinutes())}00`;
}

function getNextDayOfWeek(startDate: Date, dayName: string): Date {
  const date = new Date(startDate);
  const startDow = date.getDay(); // 0=Sun
  // Convert our day names to JS day numbers (Mon=1, Tue=2, etc)
  const targetDow = (DAY_OFFSET[dayName] ?? 0) + 1; // Our offset is Mon=0, so +1 for JS
  let diff = targetDow - startDow;
  if (diff < 0) diff += 7;
  date.setDate(date.getDate() + diff);
  return date;
}

function generateICS(
  variant: TimetableVariant,
  constraints: SchedulerConstraints,
  semesterStart: string,
  semesterEnd: string
): string {
  const startDate = new Date(semesterStart);
  const endDate = new Date(semesterEnd);
  const endDateStr = formatICSDate(endDate);

  const lines: string[] = [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//Schedulr AI//Timetable Export//EN",
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
    `X-WR-CALNAME:${variant.name} — Schedulr AI`,
  ];

  for (const slot of variant.slots) {
    const timing = constraints.slotTimings?.find(
      (_t, i) => {
        const label = `${_t.start}–${_t.end}`;
        return label === slot.slotLabel;
      }
    );

    // Try to parse from slotLabel like "09:00–09:50"
    const match = slot.slotLabel.match(/(\d{2}:\d{2})\s*[–-]\s*(\d{2}:\d{2})/);
    const startTime = match?.[1] ?? "09:00";
    const endTime = match?.[2] ?? "09:50";

    const dayCode = DAY_MAP[slot.day];
    if (!dayCode) continue;

    const firstOccurrence = getNextDayOfWeek(startDate, slot.day);
    const [startH, startM] = startTime.split(":").map(Number);
    const [endH, endM] = endTime.split(":").map(Number);

    firstOccurrence.setHours(startH, startM, 0, 0);
    const eventEnd = new Date(firstOccurrence);
    eventEnd.setHours(endH, endM, 0, 0);

    const uid = `${slot.day}-${slot.slotLabel}-${slot.subject}-${Date.now()}@schedulr.ai`;

    lines.push("BEGIN:VEVENT");
    lines.push(`UID:${uid}`);
    lines.push(`DTSTART:${formatICSDate(firstOccurrence)}`);
    lines.push(`DTEND:${formatICSDate(eventEnd)}`);
    lines.push(`RRULE:FREQ=WEEKLY;BYDAY=${dayCode};UNTIL=${endDateStr}`);
    lines.push(`SUMMARY:${slot.subject}`);
    lines.push(
      `DESCRIPTION:Faculty: ${slot.faculty}\\nRoom: ${slot.room}\\nGenerated by Schedulr AI`
    );
    lines.push(`LOCATION:${slot.room}`);
    lines.push("STATUS:CONFIRMED");
    lines.push("END:VEVENT");
  }

  lines.push("END:VCALENDAR");
  return lines.join("\r\n");
}

export function CalendarExportDialog({
  open,
  onOpenChange,
  variant,
  constraints,
  slotLabels,
}: CalendarExportDialogProps) {
  const today = new Date();
  const defaultStart = today.toISOString().split("T")[0];
  const defaultEnd = new Date(today.getTime() + 120 * 24 * 60 * 60 * 1000)
    .toISOString()
    .split("T")[0];

  const [semesterStart, setSemesterStart] = useState(defaultStart);
  const [semesterEnd, setSemesterEnd] = useState(defaultEnd);
  const [generating, setGenerating] = useState(false);
  const [syncing, setSyncing] = useState(false);

  const handleGoogleSync = async () => {
    if (!variant) return;
    if (!semesterStart || !semesterEnd) {
      toast.error("Please set both start and end dates.");
      return;
    }

    setSyncing(true);

    try {
      const response = await fetch("/api/export/google-calendar", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          variant,
          constraints,
          semesterStart,
          semesterEnd,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        toast.error(data.message || "Failed to sync to Google Calendar.");
        return;
      }

      toast.success(
        `Synced! Created calendar and added ${data.eventsCreated} events. Redirecting...`
      );
      if (data.calendarLink) {
        setTimeout(() => {
          window.location.href = data.calendarLink;
        }, 1500);
      }
    } catch (error) {
       toast.error("Network error during sync.");
    } finally {
      setSyncing(false);
    }
  };

  const handleExport = () => {
    if (!variant) return;
    if (!semesterStart || !semesterEnd) {
      toast.error("Please set both start and end dates.");
      return;
    }

    setGenerating(true);

    try {
      const icsContent = generateICS(variant, constraints, semesterStart, semesterEnd);
      const blob = new Blob([icsContent], { type: "text/calendar;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `${variant.name.replace(/\s+/g, "_")}_timetable.ics`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      toast.success(
        `Calendar file downloaded! Import it into Google Calendar, Outlook, or Apple Calendar.`
      );
    } catch {
      toast.error("Failed to generate calendar file.");
    } finally {
      setGenerating(false);
    }
  };

  const eventCount = variant?.slots.length ?? 0;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="glass-card sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <CalendarPlus className="h-5 w-5 text-cyan-400" />
            Export to Calendar
          </DialogTitle>
          <DialogDescription>
            Download an .ics file to import your timetable into Google Calendar,
            Outlook, or Apple Calendar.
          </DialogDescription>
        </DialogHeader>

        <div className="mt-4 space-y-5">
          {variant ? (
            <>
              <div className="rounded-lg border border-brand-border/40 bg-card/50 p-4">
                <div className="mb-2 flex items-center justify-between">
                  <h4 className="text-sm font-semibold text-brand-text">
                    {variant.name}
                  </h4>
                  <Badge variant="secondary" className="text-[10px]">
                    Score: {variant.score}%
                  </Badge>
                </div>
                <div className="grid grid-cols-2 gap-2 text-xs text-brand-text-secondary">
                  <span>📅 {eventCount} weekly events</span>
                  <span>🔁 Recurring weekly</span>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1.5">
                  <Label className="text-xs">Semester Start</Label>
                  <Input
                    type="date"
                    value={semesterStart}
                    onChange={(e) => setSemesterStart(e.target.value)}
                  />
                </div>
                <div className="space-y-1.5">
                  <Label className="text-xs">Semester End</Label>
                  <Input
                    type="date"
                    value={semesterEnd}
                    onChange={(e) => setSemesterEnd(e.target.value)}
                  />
                </div>
              </div>

              <div className="rounded-lg border border-cyan-500/20 bg-cyan-500/5 p-3 text-xs text-brand-text-secondary">
                <p className="mb-1 font-medium text-brand-text">How it works:</p>
                <ol className="list-decimal space-y-0.5 pl-4">
                  <li>Click &quot;Download .ics&quot; to get the calendar file</li>
                  <li>Open the file or import it in your calendar app</li>
                  <li>
                    Events will repeat weekly from{" "}
                    {semesterStart ? new Date(semesterStart).toLocaleDateString() : "start"}{" "}
                    to {semesterEnd ? new Date(semesterEnd).toLocaleDateString() : "end"}
                  </li>
                </ol>
              </div>

              <div className="grid grid-cols-2 gap-2">
                <Button
                  variant="outline"
                  className="w-full text-brand-text hover:bg-muted"
                  disabled={generating || syncing || !semesterStart || !semesterEnd}
                  onClick={handleExport}
                >
                  {generating ? (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  ) : (
                    <Download className="mr-2 h-4 w-4" />
                  )}
                  {generating ? "Generating..." : "Download .ics"}
                </Button>

                <Button
                  className="w-full bg-gradient-to-r from-blue-600 to-indigo-600 text-white hover:from-blue-700 hover:to-indigo-700"
                  disabled={generating || syncing || !semesterStart || !semesterEnd}
                  onClick={handleGoogleSync}
                >
                  {syncing ? (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  ) : (
                    <CalendarPlus className="mr-2 h-4 w-4" />
                  )}
                  {syncing ? "Syncing..." : "Sync to Google"}
                </Button>
              </div>

              <div className="grid grid-cols-3 gap-2 text-center text-[10px] text-brand-text-secondary">
                <div className="rounded-md border border-brand-border/30 p-2">
                  📱 Google Calendar
                </div>
                <div className="rounded-md border border-brand-border/30 p-2">
                  📧 Outlook
                </div>
                <div className="rounded-md border border-brand-border/30 p-2">
                  🍎 Apple Calendar
                </div>
              </div>
            </>
          ) : (
            <div className="flex h-32 flex-col items-center justify-center text-center text-brand-text-secondary">
              <CalendarPlus className="mb-3 h-10 w-10 opacity-20" />
              <p className="text-sm">Generate a timetable first to export it.</p>
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}


